### ISSUE TITLE
In the introduction to functional parsing flush is used before it is explained

### ISSUE THREAD

**Issue by dvberkel** [parallelwindfarms/byteparsing#20]
The documentation is a very thorough introduction to functional parsing and shows beautifully how this can be done with Python.

The introduction of a `Cursor` and an `Auxialiary` object shows great potential. One of the final examples in the [Auxiliary state](https://parallelwindfarms.github.io/byteparsing/functional.html#Auxiliary-state) section, the flush capability of the cursor is used before it is introduced.

This makes the example hard to understand and detracts from the power of exposition.

**Comment by jhidding** [comment]
I replaced the example with a simpler one, close this for now.
