### ISSUE TITLE
Do we really need from_bytes?

### ISSUE THREAD

**Issue by PabRod** [parallelwindfarms/byteparsing#7]
## Minor suggestion

Take a look at this method in the `Cursor` `dataclass`:

https://github.com/parallelwindfarms/byteparsing/blob/adecfae2be86c042322db3f0d8a20a87c7d0f87d/byteparsing/cursor.py#L49-L53

Wouldn't it be clearer if we set `begin` and `end` equal to 0 by default, so `Cursor(data)` does this for us?

**Comment by jhidding** [comment]
This is a matter of style. We can do both.
